import '../home_training_result.dart';
import 'retry_file_selection.dart';

enum TaskCenterCoarseStatus { inProgress, pendingReview, completed, error }

/// Safe projection, independent of mutable infrastructure attempt enums.
enum TaskCenterDetailedStatus {
  queued,
  running,
  cancelRequested,
  cancelled,
  readyForReview,
  completed,
  failed,
  interrupted,
}

enum TaskCenterEventKind {
  queuedAt,
  startedAt,
  parsedAt,
  completedAt,
  failedAt
}

final class TaskCenterEventTime {
  TaskCenterEventTime({required this.kind, required this.utcSeconds}) {
    requireHomeTrainingInput(
        utcSeconds == null || (kind != null && utcSeconds! >= 0));
  }
  final TaskCenterEventKind? kind;

  /// Missing historical time remains null, never substituted with createdAt
  /// or legacy completedAt. Cancelled/interrupted do not masquerade as failed.
  final int? utcSeconds;
}

final class TaskCenterCounts {
  TaskCenterCounts({required this.questionCount, required this.warningCount}) {
    requireHomeTrainingInput(questionCount == null || questionCount! >= 0);
    requireHomeTrainingInput(warningCount == null || warningCount! >= 0);
  }
  final int? questionCount;
  final int? warningCount;
}

final class TaskCenterActionEligibility {
  const TaskCenterActionEligibility(
      {required this.cancel,
      required this.retry,
      required this.delete,
      required this.review,
      required this.clearCompleted});
  final bool cancel;
  final bool retry;
  final bool delete;
  final bool review;
  final bool clearCompleted;
}

/// Immutable safe read projection. No raw diagnostics/error/provider content,
/// mutable task, storage row, platform object or source location is retained.
final class TaskCenterItem {
  TaskCenterItem({
    required this.target,
    required this.fileDisplayName,
    required this.status,
    required this.counts,
    required this.eventTime,
    required this.actions,
  }) {
    requireHomeTrainingInput(isSafeTaskCenterToken(fileDisplayName));
    final expectedEvent = switch (status) {
      TaskCenterDetailedStatus.queued => TaskCenterEventKind.queuedAt,
      TaskCenterDetailedStatus.running ||
      TaskCenterDetailedStatus.cancelRequested =>
        TaskCenterEventKind.startedAt,
      TaskCenterDetailedStatus.readyForReview => TaskCenterEventKind.parsedAt,
      TaskCenterDetailedStatus.completed => TaskCenterEventKind.completedAt,
      TaskCenterDetailedStatus.failed => TaskCenterEventKind.failedAt,
      TaskCenterDetailedStatus.cancelled ||
      TaskCenterDetailedStatus.interrupted =>
        null,
    };
    requireHomeTrainingInput(eventTime.kind == expectedEvent);
    requireHomeTrainingInput(!actions.clearCompleted ||
        status == TaskCenterDetailedStatus.completed);
    requireHomeTrainingInput(
        !actions.review || status == TaskCenterDetailedStatus.readyForReview);
  }
  final TaskCenterTaskTarget target;
  final String fileDisplayName;
  final TaskCenterDetailedStatus status;
  final TaskCenterCounts counts;
  final TaskCenterEventTime eventTime;
  final TaskCenterActionEligibility actions;

  TaskCenterCoarseStatus get coarseStatus => switch (status) {
        TaskCenterDetailedStatus.queued ||
        TaskCenterDetailedStatus.running ||
        TaskCenterDetailedStatus.cancelRequested =>
          TaskCenterCoarseStatus.inProgress,
        TaskCenterDetailedStatus.readyForReview =>
          TaskCenterCoarseStatus.pendingReview,
        TaskCenterDetailedStatus.completed => TaskCenterCoarseStatus.completed,
        TaskCenterDetailedStatus.cancelled ||
        TaskCenterDetailedStatus.failed ||
        TaskCenterDetailedStatus.interrupted =>
          TaskCenterCoarseStatus.error,
      };
}

final class TaskCenterSnapshot {
  TaskCenterSnapshot(Iterable<TaskCenterItem> items)
      : items = List.unmodifiable(items) {
    requireHomeTrainingInput(
        this.items.map((item) => item.target.taskId).toSet().length ==
            this.items.length);
  }
  final List<TaskCenterItem> items;
}

/// Captured eligible completed records only, generated by the query authority
/// before user confirmation. No broad 'completed + error' cleanup operation.
final class TaskCenterCompletedSnapshot {
  TaskCenterCompletedSnapshot(
      {required this.snapshotId,
      required Iterable<TaskCenterTaskTarget> targets})
      : targets = List.unmodifiable(targets) {
    requireHomeTrainingInput(isSafeTaskCenterToken(snapshotId));
    requireHomeTrainingInput(
        this.targets.map((target) => target.taskId).toSet().length ==
            this.targets.length);
  }
  final String snapshotId;
  final List<TaskCenterTaskTarget> targets;
}

final class TaskCenterCleanupResult {
  TaskCenterCleanupResult(
      {required this.deletedCount, required this.retainedCount}) {
    requireHomeTrainingInput(deletedCount >= 0 && retainedCount >= 0);
  }
  final int deletedCount;
  final int retainedCount;
}

final class TaskCenterReviewNavigationRequest {
  const TaskCenterReviewNavigationRequest(this.target);
  final TaskCenterTaskTarget target;
}

sealed class TaskCenterRetryResult {
  const TaskCenterRetryResult();
}

final class TaskCenterRetryAccepted extends TaskCenterRetryResult {
  const TaskCenterRetryAccepted();
}

final class TaskCenterRetryNeedsFileSelection extends TaskCenterRetryResult {
  const TaskCenterRetryNeedsFileSelection(this.request);
  final RetryFileSelectionRequest request;
}

final class TaskCenterRetryFailed extends TaskCenterRetryResult {
  const TaskCenterRetryFailed(this.failure);
  final HomeTrainingFailure failure;
}

abstract interface class TaskCenterQuery {
  Future<HomeTrainingResult<TaskCenterSnapshot>> read();
  Future<HomeTrainingResult<TaskCenterItem>> detail(String taskId);
  Future<HomeTrainingResult<TaskCenterCompletedSnapshot>>
      snapshotCompletedForCleanup();
}

/// All commands revalidate captured identity/attempt/revision and current action
/// eligibility/leases. Failures are typed and zero mutation. Accepted retry
/// follows existing attempt increment/token rules and resets current-attempt
/// timestamps. Review navigation is a target request, not parsed review data;
/// its composition bridge preserves existing review CAS/lease/commit authority.
abstract interface class TaskCenterCommand {
  Future<HomeTrainingResult<HomeTrainingUnit>> cancel(
      TaskCenterTaskTarget target);
  Future<TaskCenterRetryResult> retry(TaskCenterTaskTarget target);
  Future<HomeTrainingResult<HomeTrainingUnit>> delete(
      TaskCenterTaskTarget target);

  /// After explicit confirmation, revalidate each captured member as still
  /// completed/current-attempt/non-busy/non-leased. Retain all newly completed
  /// tasks outside this snapshot and all changed/noneligible snapshot members.
  /// Deletes only durable task records, never saved learning/source-file data.
  Future<HomeTrainingResult<TaskCenterCleanupResult>> clearCompleted(
      TaskCenterCompletedSnapshot snapshot);
  Future<HomeTrainingResult<TaskCenterReviewNavigationRequest>> requestReview(
      TaskCenterTaskTarget target);
}
